version: '3.8'

volumes:
  db-data:
    external: false
  redis-data:
    external: false

services:
  postgres:
    container_name: dev_mingle_postgres
    image: postgis/postgis
    platform: linux/amd64
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: dev_mingle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: dev_mingle_redis
    image: redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"
    env_file: .env
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  api:
    container_name: dev_mingle_api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILE: ${SPRING_PROFILE}
    env_file: .env
    restart: always
