version: '3.8'

volumes:
  db-data:
    external: false

services:
  api:
    container_name: dev_mingle_api
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILE: ${SPRING_PROFILE}
    env_file: .env
