spring.config.activate.on-profiles: datasource

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:dev_mingle_postgres}:5432/dev_mingle?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST:dev_mingle_redis}
    port: 6379
    password: ${REDIS_PASSWORD}
    ssl: false
    cache-database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 5000
        min-idle: 4
    timeout: 5000