spring.config.activate.on-profiles: local

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true # 색 추가
        use_sql_comments: true # jpql 추가
        default_batch_fetch_size: 100
    generate-ddl: false
    open-in-view: false

# logging 설정
logging:
  level:
    org:
      springframework: info
      hibernate.orm.jdbc.bind: trace # 바인딩 변수 확인
    com.example.wpob: debug
  file:
    name: /app/logs/local.log # 로그파일 위치

# spring actuator 설정
management:
  endpoint:
    health:
      show-details: always  # 자세한 로깅
    web:
      base-path: /actuator
      exposure:
        include: health, info, conditions, mappings, metrics, beans, env, httptrace, loggers