server:
  port: 8080

spring:
  profiles:
    include: auth, datasource, local

  output:
    ansi:
      enabled: detect # 콘솔 로그 색상 출력

api:
  path:
    default: /api/v1
#  jwt:
#    secret: ${JWT_SECRET}
#    expire: ${JWT_EXPIRE:600} # seconds
