# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: UnitTest

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 1. Build Gradle & Test
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }} # main, develop 브랜치가 아닐때만 true

    # 2. Upload Jacoco Report
    - name: Upload a Build Artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3.1.3
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html
