# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: UnitTest

on:
  pull_request:
    branches:
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 1. Build Gradle & Test
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }} # main, develop 브랜치가 아닐때만 true

    # 2. Upload Jacoco Report
    - name: Upload a Build Artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3.1.3
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html

    env:
      SPRING_PROFILE: ${{ secrets.SPRING_PROFILE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_SSL: ${{ secrets.REDIS_SSL }}
      REDIS_DATABASE: ${{ secrets.REDIS_DATABASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_SECRET: ${{ secrets.MAIL_SECRET }}
      COLUMN_ENCRYPT: ${{ secrets.COLUMN_ENCRYPT }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}